# "$schema" = "https://mise.jdx.dev/schema/mise.json"
[tools]
adr-tools = "latest"
age = "latest"
aws-sam-cli = "latest"
bun = "1.1"
elixir = "1.19"
erlang = "28.3"
flyctl = "latest"
fnox = "latest"
gcloud = "latest"
go = "1.23"
helm = "latest"
java = "openjdk-17"
jj = "latest"
kubectl = "latest"
lua-language-server = "latest"
mage = "latest"
neovim = "ref:nightly"
node = "lts"
pkl = "latest"
python = "3.12"
rust = "stable"
taplo = "latest"  # toml lsp
terraform = "latest"
tree-sitter = "latest"
usage = "latest"
uv = "latest"
vault = "latest"

"asdf:awscli" = "latest"

"cargo:git-global" = "latest"
# interactive rg replacer
"cargo:rep-grep" = "latest"

# npm
"npm:@charmland/crush" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@neovate/code" = "latest"
"npm:@qwen-code/qwen-code" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:fkill-cli" = "latest"
"npm:vscode-langservers-extracted" = "latest"

# pipx/uvx
# "pipx:mlx-omni-server" = "latest"
"pipx:claude-monitor" = "latest"
"pipx:httpie" = "latest"
"pipx:litellm" = { version = "latest", extras = "proxy" }
"pipx:llm" = "latest"
"pipx:mistral-vibe" = "latest"
"pipx:pipenv" = "latest"
"pipx:tiptop" = "latest"
"pipx:yq" = "latest"

"ubi:RhetTbull/osxphotos" = "latest"
"ubi:achristmascarl/rainfrog" = "latest"
"ubi:block/goose" = "latest"
"ubi:pls-rs/pls" = "v0.0.1-beta.9"
"ubi:sst/opencode" = "latest"
arduino-cli = "latest"
"npm:@kilocode/cli" = "latest"
"go:github.com/steveyegge/beads/cmd/bd" = "latest"
claude-code = { version = "latest", bin = "claude", platforms = """
[linux-arm64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{{ version }}/linux-arm64/claude"

[linux-x64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{{ version }}/linux-x64/claude"

[macos-arm64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{{ version }}/darwin-arm64/claude"

[macos-x64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{{ version }}/darwin-x64/claude"

[windows-x64]
bin = "claude.exe"
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{{ version }}/win32-x64/claude.exe"
""", version_list_url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/latest" }
"pipx:md2pdf-mermaid" = "latest"

[settings]
go_default_packages_file = "./default-go-packages"
experimental = true
idiomatic_version_file_enable_tools = ["node", "python"]

[settings.node]
gpg_verify = true

[settings.pipx]
uvx = true

[settings.python]
default_packages_file = "./default-python-packages"
uv_venv_auto = true

[settings.status]
show_env = true
show_tools = false

[settings.swift]
gpg_verify = true

# TODO: remove?
# [plugins]
# asdf-awscli = "https://github.com/MetricMike/asdf-awscli.git"
# clang = "https://github.com/mise-plugins/mise-llvm.git"
# cmake = "https://github.com/mise-plugins/mise-cmake.git"
# gcloud = "https://github.com/jthegedus/asdf-gcloud.git"
# maven = "https://github.com/mise-plugins/asdf-maven.git"
# nasm = "https://github.com/mise-plugins/mise-nasm.git"
# pipx = "https://github.com/yozachar/asdf-pipx.git"
# poetry = "https://github.com/mise-plugins/mise-poetry.git"
# postgres = "https://github.com/smashedtoatoms/asdf-postgres.git"
# yarn = "https://github.com/mise-plugins/asdf-yarn.git"
