# "$schema" = "https://mise.jdx.dev/schema/mise.json"
[tools]
adr-tools = "latest"
age = "latest"
aws-sam-cli = "latest"
bun = "latest"
elixir = "latest"
erlang = "latest"
flyctl = "latest"
fnox = "latest"
gcloud = "latest"
go = "latest"
helm = "latest"
java = "openjdk-17"
jj = "latest"
kubectl = "latest"
lua-language-server = "latest"
mage = "latest"
neovim = "ref:nightly"
node = "lts"
pkl = "latest"
python = "3.12"
rust = "stable"
taplo = "latest"
terraform = "latest"
tree-sitter = "latest"
usage = "latest"
uv = "latest"
vault = "latest"
"npm:@google/gemini-cli" = "latest"

"asdf:awscli" = "latest"

# interactive rg replacer
"cargo:rep-grep" = "latest"

# npm
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@astrojs/language-server" = "latest"
"npm:@charmland/crush" = "latest"
"npm:@neovate/code" = "latest"
"npm:@qwen-code/qwen-code" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"

# pipx/uvx
"pipx:claude-monitor" = "latest"
"pipx:httpie" = "latest"
"pipx:litellm" = { version = "latest", extras = "proxy" }
"pipx:llm" = "latest"
# "pipx:mlx-omni-server" = "latest"
"pipx:pipenv" = "latest"
"pipx:tiptop" = "latest"
"pipx:yq" = "latest"

"ubi:RhetTbull/osxphotos" = "latest"
"ubi:achristmascarl/rainfrog" = "latest"
"ubi:block/goose" = "latest"
"ubi:sst/opencode" = "latest"

[settings]
go_default_packages_file = "./default-go-packages"
experimental = true
idiomatic_version_file_enable_tools = []

[settings.node]
gpg_verify = true

[settings.pipx]
uvx = true

[settings.python]
default_packages_file = "./default-python-packages"
uv_venv_auto = true

[settings.status]
show_env = true
show_tools = false

[settings.swift]
gpg_verify = true

# TODO: remove?
# [plugins]
# asdf-awscli = "https://github.com/MetricMike/asdf-awscli.git"
# clang = "https://github.com/mise-plugins/mise-llvm.git"
# cmake = "https://github.com/mise-plugins/mise-cmake.git"
# gcloud = "https://github.com/jthegedus/asdf-gcloud.git"
# maven = "https://github.com/mise-plugins/asdf-maven.git"
# nasm = "https://github.com/mise-plugins/mise-nasm.git"
# pipx = "https://github.com/yozachar/asdf-pipx.git"
# poetry = "https://github.com/mise-plugins/mise-poetry.git"
# postgres = "https://github.com/smashedtoatoms/asdf-postgres.git"
# yarn = "https://github.com/mise-plugins/asdf-yarn.git"
